### ISSUE TITLE
usage not showing events

### ISSUE THREAD

**Issue by kra** [futel/usage#69]
Either S3 doesn't have them, or usage is not showing them.

Call starts at dialplan-functions.

metrics from the sns-reader test queue:

   3521:{"timestamp": "2024-04-27T18:21:03.855051", "hostname": "dialplan-functions-prod", "event": {"Event": "UserEvent", "endpoint": "dome-office", "Channel": "dome-office", "UserEvent": "outgoing_safe"}}
   3522:{"timestamp": "2024-04-27T18:21:07.292934", "hostname": "dialplan-functions-prod", "event": {"Event": "UserEvent", "endpoint": "dome-office", "Channel": "dome-office", "UserEvent": "dial_sip_asterisk"}}

Call continues to voicemail_outgoing on the asterisk box.

metrics logfile on the asterisk box:

2024-04-27 11:21:07,972 UNIQUEID=1714242067.3308, CHANNEL=PJSIP/twilio-00000abb, CALLERID(number)=+15034681337, name=voicemail_outgoing, endpoint=dome-office
2024-04-27 11:21:19,089 UNIQUEID=1714242067.3308, CHANNEL=PJSIP/twilio-00000abb, CALLERID(number)=+15034681337, name=voicemail_create, endpoint=dome-office

metrics from the sns-reader test queue (note unrelated one in the middle):

{"timestamp": "2024-04-27T18:21:07+00:00", "hostname": "futel-prod.phu73l.net", "event": {"Event": "UserEvent", "Privilege": "user,all", "Channel": "PJSIP/twilio-00000abb", "ChannelState": "6", "ChannelStateDesc": "Up", "CallerIDName": "dome-office", "ConnectedLineName": "<unknown>", "Language": "en", "AccountCode": "", "Context": "voicemail_outgoing", "Priority": "1", "Uniqueid": "1714242067.3308", "Linkedid": "1714242067.3308", "UserEvent": "voicemail_outgoing", "endpoint": "dome-office"}}
{"timestamp": "2024-04-27T18:19:52+00:00", "hostname": "futel-prod.phu73l.net", "event": {"Event": "contact_status_Unavail", "endpoint": "445", "Channel": "PJSIP/445"}}
{"timestamp": "2024-04-27T18:21:19+00:00", "hostname": "futel-prod.phu73l.net", "event": {"Event": "UserEvent", "Privilege": "user,all", "Channel": "PJSIP/twilio-00000abb", "ChannelState": "6", "ChannelStateDesc": "Up", "CallerIDName": "dome-office", "ConnectedLineName": "<unknown>", "Language": "en", "AccountCode": "", "Context": "voicemail_create", "Priority": "1", "Uniqueid": "1714242067.3308", "Linkedid": "1714242067.3308", "UserEvent": "voicemail_create", "endpoint": "dome-office"}}

Call returns to dialplan-functions.

metrics from the sns-reader test queue:

   3529:{"timestamp": "2024-04-27T18:21:36.470288", "hostname": "dialplan-functions-prod", "event": {"Event": "UserEvent", "endpoint": "dome-office", "Channel": "dome-office", "UserEvent": "outgoing_call"}}
   3530:{"timestamp": "2024-04-27T18:21:36.302571", "hostname": "dialplan-functions-prod", "event": {"Event": "UserEvent", "endpoint": "dome-office", "Channel": "dome-office", "UserEvent": "metric_dialer_status"}}

Looking at usage, voicemail-create (note the dash/underscore) isn't shown:

https://futel.github.io/usage/?p=dome-office&e=voicemail-create&a=hourly&si=true&start=2024-04-20&end=2024-04-28

But dial-sip-asterisk is shown:

https://futel.github.io/usage/?p=dome-office&e=dial-sip-asterisk&a=hourly&si=true&start=2024-04-20&end=2024-04-28

Either S3 doesn't have it or usage isn't showing it. Easy to check if S3 has it. The timestamps in the events jump all around relative to the actual time, I thought we were reading the timestamps from the events, is there something related to wierd timestamps maybe?

**Comment by breedx2** [comment]
The `voicemail_create` event at `11:21:19` was for channel `PJSIP/twilio-00000abb` and this event **did** make it into the s3 data, and it did make it into the [processed output](https://raw.githubusercontent.com/futel/usage/gh-pages/data/date/2024/04/20240427.json). 

```
  {
    "timestamp": "2024-04-27T18:21:19+00:00",
    "channel": "PJSIP-twilio",
    "event": "voicemail-create"
  }
```

The first usage link you pasted above is looking for this with channel `dome-office` though, which is not the same as `PJSIP-twilio`. I think that's why it doesn't show up. If you change the phone to `twilio` then it shows up:

https://futel.github.io/usage/?p=twilio&e=voicemail-create&a=hourly&si=true&start=2024-04-27&end=2024-04-27

**Comment by kra** [comment]
Ahahaha that's the problem! Now that we use dialplan-functions and also still use asteriskserver, "channel" is not always correct, but "endpoint" is. This is because "channel" has different Asterisk dependencies, and also to Asterisk a call going through dialplan-functions is an incoming call. So I just added a correct "endpoint" to every metric publish.

The issue is that the voicemail-create event had the same dome-office extension as the other events. Usage needs to read the "endpoint" attribute and fall back to "channel" for old messages which don't have it.

I think this is where that happens?
https://github.com/futel/usage/blob/main/static-gen/src/grouper.py#L14

This is where the S3 item gets channel and endpoint, I guess the channel attribute doesn't need to be written any more:
https://github.com/futel/s3-event-writer/blob/main/src/msg_mapper.py#L29

**Comment by breedx2** [comment]
Yeah ok, so the pain is migrating from a single-source consistent data model to this hybrid thing now, where some data is from twilio and some is from asterisk...but it sounds like you've done the bulk of the work already to normalize on "endpoint" being the thing that uniquely identifies a phone. Is it ALWAYS in the events, or do we still need to fall back to channel when it's not there?

Even though you tackled a little bit if this in #60, the events in S3 aren't complete because the "final" rendering to s3 is [here](https://github.com/futel/s3-event-writer/blob/main/src/msg_mapper.py#L15) and it doesn't write endpoint!

I think we can just add endpoint to that json wad in `map_final` and then the events in S3 will contain the `endpoint` field, because right now they *only* have channel. :facepalm:

**Comment by kra** [comment]
AAAAAAAAA this is what you get when trying to make gradual change across schemaless persistent crap without using any organization!

**Comment by kra** [comment]
This is a s3-event-writer issue I think!
